/**
 * optimize-gallery.mjs
 *
 * Generates optimized image variants (AVIF, WebP, JPEG) for the public gallery,
 * plus a tiny LQIP (blur-up placeholder) data URI and a typed manifest consumed
 * by the React gallery island.
 *
 * Outputs into public/gallery/optimized/:
 *   - {id}-640.{avif,webp,jpg}   grid thumbnail (mobile)
 *   - {id}-1600.{avif,webp,jpg}  grid thumbnail (desktop / 2x)
 *   - {id}-2000.{avif,webp,jpg}  lightbox (replaces multi-MB originals)
 *
 * Also emits src/data/gallery-manifest.ts with the LQIP data URI, aspect ratio
 * and lightbox dimensions per image.
 *
 * Idempotent: skips any output file that already exists and is newer than its
 * source. Safe to run repeatedly and in CI. Delete public/gallery/optimized to
 * force a full re-generation.
 *
 * Usage:  node scripts/optimize-gallery.mjs
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC_DIR = path.join(ROOT, "public", "gallery");
const OUT_DIR = path.join(SRC_DIR, "optimized");
const MANIFEST_PATH = path.join(ROOT, "src", "data", "gallery-manifest.ts");

// Grid: 640 (mobile) + 1600 (desktop / 2x). Lightbox: 2000 (replaces 4080px).
const WIDTHS = [640, 1600, 2000];
const LQIP_WIDTH = 20;

// Per-format encode settings. ext is the file extension; method is the sharp
// pipeline method name (sharp exposes `.jpeg`, not `.jpg`).
const FORMATS = [
  { ext: "avif", method: "avif", opts: { quality: 38, effort: 4 } },
  { ext: "webp", method: "webp", opts: { quality: 72 } },
  { ext: "jpg", method: "jpeg", opts: { quality: 78, mozjpeg: true, progressive: true } },
];

async function isNewer(outPath, srcMtimeMs) {
  try {
    const st = await fs.stat(outPath);
    return st.mtimeMs >= srcMtimeMs;
  } catch {
    return false;
  }
}

async function ensureVariant(srcPath, srcMtimeMs, id, width, format) {
  const outPath = path.join(OUT_DIR, `${id}-${width}.${format.ext}`);
  if (await isNewer(outPath, srcMtimeMs)) return;
  const pipeline = sharp(srcPath, { failOn: "none" })
    .rotate()
    .resize({ width, withoutEnlargement: true });
  await pipeline[format.method](format.opts).toFile(outPath);
}

async function processSource(fileName) {
  if (!/\.jpe?g$/i.test(fileName)) return null;
  const id = path.basename(fileName, path.extname(fileName));
  const srcPath = path.join(SRC_DIR, fileName);
  const { mtimeMs } = await fs.stat(srcPath);

  const meta = await sharp(srcPath).metadata();
  const aspectRatio = meta.width / meta.height;

  for (const width of WIDTHS) {
    for (const format of FORMATS) {
      await ensureVariant(srcPath, mtimeMs, id, width, format);
    }
  }

  // LQIP — 20px JPEG data URI (universally supported as a CSS background).
  const lqipBuf = await sharp(srcPath, { failOn: "none" })
    .rotate()
    .resize({ width: LQIP_WIDTH, withoutEnlargement: true })
    .jpeg({ quality: 30, mozjpeg: true, progressive: false })
    .toBuffer();
  const lqip = `data:image/jpeg;base64,${lqipBuf.toString("base64")}`;

  // Lightbox (2000w) pixel dimensions for PhotoSwipe.
  const fullHeight = Math.round(2000 / aspectRatio);

  return [id, { lqip, aspectRatio, full: { width: 2000, height: fullHeight } }];
}

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });
  await fs.mkdir(path.dirname(MANIFEST_PATH), { recursive: true });

  const entries = await fs.readdir(SRC_DIR, { withFileTypes: true });
  const sources = entries.filter((e) => e.isFile()).map((e) => e.name);

  const manifest = {};
  for (const name of sources) {
    const result = await processSource(name);
    if (!result) continue;
    manifest[result[0]] = result[1];
    console.log(`✓ ${result[0]}`);
  }

  const ts =
    `// AUTO-GENERATED by scripts/optimize-gallery.mjs — do not edit by hand.\n` +
    `export interface GalleryManifestEntry {\n` +
    `  lqip: string;\n` +
    `  aspectRatio: number;\n` +
    `  full: { width: number; height: number };\n` +
    `}\n` +
    `const manifest: Record<string, GalleryManifestEntry> = ${JSON.stringify(manifest, null, 2)};\n` +
    `export default manifest;\n`;
  await fs.writeFile(MANIFEST_PATH, ts, "utf8");

  console.log(
    `\nManifest written: ${path.relative(ROOT, MANIFEST_PATH)} ` +
      `(${Object.keys(manifest).length} images)`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
